version: '3.4'
services:
  eventbus:
     image: rabbitmq:3.7-management
     container_name: citibank.eventbus
     environment:
       RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
       RABBITMQ_DEFAULT_USER: rabbitmq
       RABBITMQ_DEFAULT_PASS: rabbitmq
       RABBITMQ_DEFAULT_VHOST: "/"
     hostname: eventbus
     volumes:
       - volume_eventbus:/var/lib/rabbitmq
       - ./rabbitmq_init/definitions.json:/etc/rabbitmq/definitions.json
     ports:
       - "7000:15672"
       - "7001:5672"
  eventstore:
     image: mysql:5.7.17
     container_name: citibank.eventstore
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: eventstore
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: alemol*
     ports:
       - "3360:3306"
     volumes:
       - volume_eventstore:/var/lib/mysql
       - ./db-init-eventstore:/docker-entrypoint-initdb.d/
     restart: always
  view:
     image: mysql:5.7.17
     container_name: citibank.view
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: view
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: alemol*
     ports:
       - "3366:3306"
     volumes:
       - volume_view:/var/lib/mysql
       - ./db-init-view:/docker-entrypoint-initdb.d/
     restart: always
volumes:
    volume_view:
       name: demo-view
       external: false
    volume_eventstore:
       name: demo-eventstore
       external: false
    volume_eventbus:
       name: demo-eventbus
       external: false